### ISSUE TITLE
Provide richer API for modules

### ISSUE THREAD

**Issue by ZeHiro** [Phyks/cozyweboob#5]
E.g. : 
For the bill capability, in order not to download all the bills each time, it could be interesting to have 2 routes: 
/fetch : will return the list of bills
/download : will download the bill id passed in parameter.
Maybe it could be interesting to map the API with the function exposed by each module: 
http://dev.weboob.org/api/capabilities/bill.html?highlight=capbill#weboob.capabilities.bill.CapBill

**Comment by Phyks** [comment]
I want to support all the available capabilities, so I don't think mapping exactly to the CapBill API is a good idea.

Download endpoint is indeed a requirement and was to be added soon though. Also note that in the output JSON, the cookie JAR is exported so that a client side script can also download the bills itself.

**Comment by Phyks** [comment]
@ZeHiro I started to work on it in [this commit](https://github.com/Phyks/cozyweboob/commit/ee677ab6d23aeffefb9064da41cfb47a8972ae53). I still have the download route to implement.

Not sure also about the best way to pass back the downloaded files to the client :/
